import Link from "next/link";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useColorMode } from "@chakra-ui/react";
import { MoonIcon, SunIcon } from "@chakra-ui/icons";
import { Image } from "@chakra-ui/react";
import {
  Flex,
  Center,
  Box,
  Button,
  Stack,
  VStack,
  HStack,
  Title,
} from "@chakra-ui/react";
import LinkButton from "./LinkButton";

export default ({ children }) => {
  const { colorMode, toggleColorMode } = useColorMode();
  return (
    <div>
      <Head>
        <title>Book Djinni</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/genie-lamp-10-16.png" />
      </Head>
      {/* navbar */}
      <Flex justifyContent="space-between" ml={2}>
        <Link href="/">Home</Link>

        <Link href="/play">
          <a href="/play">
            <img
              width="90px"
              // height="50px"
              src={
                colorMode === "light" ? "/lamp_dark_1.svg" : "lamp_light_1.svg"
              }
              alt="Rub!"
            />
            {/* <img src="lamp_light.svg" alt="Rub!" /> */}
          </a>
        </Link>
        <Box>
          <Link href="/about">
            <a>About</a>
          </Link>

          <Button onClick={toggleColorMode} bg="transparent">
            {" "}
            {colorMode === "light" ? <MoonIcon /> : <SunIcon />}
          </Button>
        </Box>
      </Flex>
      {/* main content */}
      {children}
      {/* footer content */}
      <footer className={styles.footer}>powered by magic & mate</footer>
    </div>
  );
};

// colors generatated with Korma ai:
// http://khroma.co/generator/
