import Link from "next/link";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export default ({ children }) => (
  <div className={styles.container}>
    <Head>
      <title>Book Djinni</title>
      {/* <meta name="description" content="Generated by create next app" /> */}
      <link rel="icon" href="/genie-lamp-10-16.png" />
    </Head>
    <header>
      <Link href="/">
        <a>Home</a>
      </Link>
      <Link href="/about">
        <a>About</a>
      </Link>
    </header>
    {children}
    <footer className={styles.footer}>powered by magic & mate</footer>
    <style jsx>{`
      .root {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
      }
      header {
        width: 100%;
        display: flex;
        justify-content: space-around;
        padding: 1em;
        font-size: 1.2rem;
        background: #9867c5;
      }
      header a {
        color: darkgrey;
        text-decoration: none;
      }
      header a:hover {
        font-weight: bold;
        color: lightgrey;
      }
      footer {
        padding: 1em;
      }
    `}</style>
  </div>
);
