import Link from "next/link";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useColorMode } from "@chakra-ui/react";
import { Button } from "@chakra-ui/react";
import { MoonIcon, SunIcon } from "@chakra-ui/icons";

export default ({ children }) => {
  const { colorMode, toggleColorMode } = useColorMode();
  return (
    <div className={styles.container}>
      <Head>
        <title>Book Djinni</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/genie-lamp-10-16.png" />
      </Head>
      <header>
        <Link href="/">
          <a>Home</a>
        </Link>
        <Link href="/about">
          <a>About</a>
        </Link>
        {/* <Button onClick={toggleColorMode}>
          {colorMode === "light" ? <MoonIcon /> : <SunIcon />}
        </Button> */}
      </header>
      {children}
      <footer className={styles.footer}>powered by magic & mate</footer>
      <style jsx>{`
        .root {
          display: flex;
          justify-content: center;
          align-items: center;
          flex-direction: column;
        }
        header {
          width: 100%;
          display: flex;
          justify-content: space-around;
          padding: 1em;
          font-size: 1.2rem;
          background: #b8d1d9;
        }
        header a {
          color: #7d30e2;
          text-decoration: none;
        }
        header a:hover {
          font-weight: bold;
          color: lightgrey;
        }
        footer {
          padding: 1em;
        }
      `}</style>
    </div>
  );
};

// colors generatated with Korma ai:
// http://khroma.co/generator/
